name: CI

on:
  push:
    branches: master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn

  typecheck:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Typecheck
        run: yarn tsc

  lint:
    runs-on: [ubuntu-latest]
    needs: [setup]
    steps:
      - name: lint
        run: yarn lint

  test:
    runs-on: [ubuntu-latest]
    needs: [setup]
    steps:
      - name: lint
        run: yarn test

  release:
    runs-on: [ubuntu-latest]
    needs: [typecheck,lint,test]
    steps:
      - run: echo "Release!"
