name: CI

on:
    push:
        branches: [master]

jobs:
    setup:
        runs-on: [ubuntu-latest]
        steps:
            #     - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: yarn
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

    typecheck:
        runs-on: ubuntu-latest
        needs: [setup]
        steps:
            - uses: actions/checkout@v1
            # - run: yarn
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Typecheck
              run: yarn tsc

    lint:
        runs-on: [ubuntu-latest]
        needs: [setup]
        steps:
            - uses: actions/checkout@v1
            # - run: yarn
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: lint
              run: yarn lint

    test:
        runs-on: [ubuntu-latest]
        needs: [setup]
        steps:
            - uses: actions/checkout@v1
            # - run: yarn
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: lint
              run: yarn test

    release:
        runs-on: [ubuntu-latest]
        needs: [typecheck, lint, test]
        steps:
            - run: echo "Release!"
